services:
  rabbitmq:
    image: rabbitmq:4.0-management
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - ./data/rabbitmq:/var/lib/rabbitmq # 持久化数据
    environment:
      RABBITMQ_DEFAULT_USER: xll
      RABBITMQ_DEFAULT_PASS: xll
